server:
  port: 8761

spring:
  cloud:
    config:
      enabled: false  # ✅ Config Server 비활성화
      import-check:
        enabled: false  # ✅ 추가적인 import 체크 비활성화

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # ✅ 자기 자신을 Eureka에 등록하지 않음
    fetchRegistry: false       # ✅ 다른 서비스 목록을 가져오지 않음
